# Generated by Django 3.2.16 on 2022-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=45)),
                ('event_dtime', models.TextField()),
                ('file_name', models.TextField()),
                ('ori_text', models.TextField()),
                ('first_tag', models.CharField(max_length=10)),
                ('second_tag', models.CharField(max_length=10)),
                ('mod_first_tag', models.CharField(max_length=10)),
                ('mod_second_tag', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mod_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=45)),
                ('file_name', models.TextField()),
                ('new_file_name', models.TextField()),
                ('trans_dtime', models.TextField()),
                ('trans_md', models.CharField(max_length=3)),
                ('ats_kdcd_dtl', models.TextField()),
                ('ori_text', models.TextField()),
                ('pro_text', models.TextField()),
                ('first_tag', models.CharField(blank=True, max_length=10, null=True)),
                ('second_tag', models.CharField(blank=True, max_length=10, null=True)),
                ('event_dtime', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pro_table',
                'managed': False,
            },
        ),
    ]
