# Generated by Django 3.2.5 on 2022-09-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_auto_20220823_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusDictionary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('tag', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'corpus_dictionary',
                'managed': False,
            },
        ),
    ]
