# Generated by Django 3.2.5 on 2022-09-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0004_corpusdictionary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiTable',
        ),
        migrations.DeleteModel(
            name='LogTable',
        ),
    ]
