# Generated by Django 3.2.16 on 2022-10-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0005_auto_20220923_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=45)),
                ('event_dtime', models.TextField()),
                ('file_name', models.TextField()),
                ('ori_text', models.TextField()),
                ('first_tag', models.CharField(max_length=10)),
                ('second_tag', models.CharField(max_length=10)),
                ('mod_first_tag', models.CharField(max_length=10)),
                ('mod_second_tag', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mod_table',
                'managed': False,
            },
        ),
    ]
