# Generated by Django 3.2.16 on 2022-10-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0007_auto_20221031_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModTable',
        ),
    ]
