# Generated by Django 3.2.16 on 2022-10-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0008_delete_modtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProTable',
        ),
    ]
