-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 15:59:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ATS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ATS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ATS` DEFAULT CHARACTER SET utf8 ;
USE `ATS` ;

-- -----------------------------------------------------
-- Table `ATS`.`pro_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATS`.`pro_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` VARCHAR(45) NOT NULL,
  `file_name` TEXT NOT NULL,
  `new_file_name` TEXT NOT NULL,
  `trans_dtime` TEXT NOT NULL,
  `trans_md` VARCHAR(3) NOT NULL,
  `ats_kdcd_dtl` TEXT NOT NULL,
  `ori_text` TEXT NOT NULL,
  `pro_text` TEXT NOT NULL,
  `first_tag` VARCHAR(10) NULL,
  `second_tag` VARCHAR(10) NULL,
  `event_dtime` TEXT NOT NULL,
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATS`.`data_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATS`.`data_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` VARCHAR(45) NOT NULL,
  `file_name` TEXT NOT NULL,
  `new_file_name` TEXT NOT NULL,
  `start_dtime` TEXT NOT NULL,
  `end_dtime` TEXT NOT NULL,
  `data_len` TEXT NOT NULL,
  `pro_result` VARCHAR(3) NOT NULL,
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATS`.`corpus_dictionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATS`.`corpus_dictionary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `word` TEXT NOT NULL,
  `tag` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATS`.`mod_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATS`.`mod_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pro_table_id` INT NOT NULL,
  `member_id` VARCHAR(45) NOT NULL,
  `event_dtime` TEXT NOT NULL,
  `file_name` TEXT NOT NULL,
  `ori_text` TEXT NOT NULL,
  `first_tag` VARCHAR(10) NOT NULL,
  `second_tag` VARCHAR(10) NOT NULL,
  `mod_first_tag` VARCHAR(10) NOT NULL,
  `mod_second_tag` VARCHAR(10) NOT NULL,
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mod_table_pro_table_idx` (`pro_table_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_mod_table_pro_table`
    FOREIGN KEY (`pro_table_id`)
    REFERENCES `ATS`.`pro_table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
